

/* const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

import SideNav from "@/components/side-nav";
import SideNavMovile from "@/components/side-nav-movile";

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="md:container px-3  mx-auto py-12">

      <div className="flex gap-8">
        <SideNav />
        <SideNavMovile />

        {/* Archivos */}
        <div className="w-full md:pl-40">
          {children}
        </div>
      </div>
    </main>
  );
}
